on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: wangyoucao577/go-release-action@279495102627de7960cbc33434ab01a12bae144b # @v1.55
      with:
        goversion: 1.25.4
        pre_command: apt-get update && apt-get install -y libasound2-dev
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
